spring:
  datasource:
    url: jdbc:h2:mem:erpdb
    username: erpdev
    password: password123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  security:
    user:
      name: user
      password: $2a$10$oHr.wT03vHFfZkCSp3WeWu1DPBtTH2pivt.KqnJJHA3p2CsBfQphi    #pass
